### PR TITLE
new: dockerfile for local builds

### PR DESCRIPTION
**Pull request by aarroyoc**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area examples

**What this PR does / why we need it**:

It's a docker image for local builds of Falco Exporter. We need it because we plan to use it in a Kubernetes cluster and it may be interesting for others as well.

**Which issue(s) this PR fixes**:

NONE

**Special notes for your reviewer**:

It's my first PR here, so feel free to criticize the whole thing.

**Does this PR introduce a user-facing change?**: 

```release-note
new: docker image for local builds
```

### CODE REVIEW

**Comment by leodido** [comment]
Added a release note to the PR template BTW.

**Comment by Issif** [comment]
That's a nice PR, as @leodido proposed, you should use multi-stages to get slimest possible images, you can take this as example : https://github.com/falcosecurity/falcosidekick/blob/master/Dockerfile

It's also better if exporter doesn't run as root inside container.

**Comment by aarroyoc** [comment]
Updated! I think it's better to have the two `COPY` separated because it enabled better build caching (dependencies are only compiled once when doing changes). But I'm not a Go expert, so maybe this is not very useful in Go as in others languages.

**Comment by leodido** [comment]
Oh @aarroyoc you are right thinking about it, because of the go modules behavior. So this LGTM.

**Pull request merged**
