### PR TITLE
Add Mutual TLS feature

### LINKED ISSUE #47: Add mTLS (optionally) for exporter metrics endpoint
**Motivation**

Since falco-exporter could show falco alerts on its metrics endpoint, and these alerts could contain sensitive information like passwords, usernames, internal endpoints, etc... There should be a way to enable mTLS in exporter server so only allowed clients (e.g: Prometheus) is able to retrieve alerts

**Feature**

Add arguments to specify a CA file, a server certificate and implement the mTLS logic in root.go file (I'll try to fork the project and make a PR but I'm not a Go guy)

**Alternatives**

Going without TLS

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by jasiam**
Signed-off-by: Jose Angel Santiago

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area commands

**What this PR does / why we need it**:
falco-exporter may expose sensitive information through alerts (credentials, endpoints, etc...)

**Which issue(s) this PR fixes**:

Fixes #47 

**Special notes for your reviewer**:

First time with Go, I'm completely open to any improvement

### CODE REVIEW

**Comment by leogr** [comment]
Hi @jasiam 

Thanks for your contribution :+1: 
I will take a look soon, and likely I will also add a commit to update the readme.

**Review by leogr — COMMENTED** [review]
Just tried and SGTM! 

I have to say your first time with Go went very well  ;)
You did a great job :clap: 

I would ask you only one thing. Since this project uses [conventional commits messages](https://www.conventionalcommits.org/en/v1.0.0/) to autogenerate the changelog, could you amend your commit and change the message accordingly (e.g. `new: optional mutual TLS for HTTP metrics server`)?
 
Then I will be happy to approve this PR :+1: 

Thank you again.

**Comment by jasiam** [comment]
All right! This was also my first time with DCO so sorry about multiple amends, I'm not used to it.

I'm working right now in a PR for the falco-exporter helm chart so I hope this would be a much cleaner commit-history PR :-)

**Comment by leogr** [comment]
> All right! This was also my first time with DCO so sorry about multiple amends, I'm not used to it.

Thank you and no worry, you're doing it right :+1: 
 
> I'm working right now in a PR for the falco-exporter helm chart so I hope this would be a much cleaner commit-history PR :-)

sounds good, just give me some time to release this new feature first :smile_cat: 

Anyway, I have found a very small issue, I'm adding a commit then I'll approve!

**Comment by leogr** [comment]
I have just removed `tlsConfig.BuildNameToCertificate()` since it has been deprecated also seems to be ineffectual, see :point_down: 
https://github.com/falcosecurity/falco-exporter/pull/49/commits/de81b6c86c022ae6e73e5e3a7463238e7b56d4cd#diff-268ce15105756add7804b9007645d77eeb472b5f4a4cf81a38b71a9f26270bfbL114

**Review by leogr — APPROVED** [review]
Done! :+1:

**Comment by leogr** [comment]
Just released https://github.com/falcosecurity/falco-exporter/releases/tag/v0.4.0

Thank you again @jasiam !

**Pull request merged**
