### PR TITLE
cleanup(ci): dropped circleci.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
Opened https://github.com/falcosecurity/test-infra/pull/960 to drop circleci required status check.

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
Closing and reopening to trigger prow.

**Comment by FedeDP** [comment]
Mmmh why is it still expecting a 
> ci/circleci: test Expected — Waiting for status to be reported 

?

**Pull request merged**
